### ISSUE TITLE
Supress warning and critical

### ISSUE THREAD

**Issue by davixd** [rk-it-at/check_rhv#17]
Hi,
is it possible to deactivate warning and critical with a parameter? To use Hosts for statistic use only?

Many thanks in advance!

Best regards
David

**Comment by scrat14** [comment]
I'm sorry, but it's not possible to deactivate warning/critical checks. You can use very high values for warning/critical which would deactivate the check.
This could be useful, but I will not implement it, as I don't use oVirt/RHV anymore and will not release further updates for this plugin. Sorry.

**Comment by davixd** [comment]
Thank you very much Rene for developing and maintaining this check for so many years! I hope this project will stay alive and be forked.
