### ISSUE TITLE
Host network errors output bug

### ISSUE THREAD

**Issue by davixd** [rk-it-at/check_rhv#18]
Hi guys,
is it possible that the host network error command have a bug? Please have a closer look at eno1.

Icinga output:
eno1: 0.00 Errors

Perfomance data output:
errors_eno1=5000c;5;10;0; 

-a xxx -R xxx -l network -s errors

`RHV OK: errors ok - eno2: 0.00 Errors bond0.2415: 0.00 Errors bond0.174: 0.00 Errors bond0.413: 0.00 Errors bond0.2413: 0.00 Errors bond0.419: 0.00 Errors bond0.415: 0.00 Errors bond0.4: 0.00 Errors bond0.2419: 0.00 Errors bond0.423: 0.00 Errors bond0.417: 0.00 Errors bond0.2421: 0.00 Errors bond0.224: 0.00 Errors bond0.2414: 0.00 Errors bond0.2411: 0.00 Errors bond0.565: 0.00 Errors bond0.411: 0.00 Errors bond0: 0.00 Errors bond0.114: 0.00 Errors bond0.194: 0.00 Errors eno1: 0.00 Errors bond0.2417: 0.00 Errors bond0.234: 0.00 Errors bond0.134: 0.00 Errors bond0.144: 0.00 Errors bond0.25: 0.00 Errors bond0.2400: 0.00 Errors bond0.2423: 0.00 Errors bond0.2422: 0.00 Errors bond0.425: 0.00 Errors bond0.241: 0.00 Errors bond0.422: 0.00 Errors bond0.2412: 0.00 Errors bond0.154: 0.00 Errors (rhev-11.mgmt.biotronik-homemonitoring.int) |errors_eno2=0c;5;10;0; errors_bond0.2415=0c;5;10;0; errors_bond0.174=0c;5;10;0; errors_bond0.413=0c;5;10;0; errors_bond0.2413=0c;5;10;0; errors_bond0.419=0c;5;10;0; errors_bond0.415=0c;5;10;0; errors_bond0.4=0c;5;10;0; errors_bond0.2419=0c;5;10;0; errors_bond0.423=0c;5;10;0; errors_bond0.417=0c;5;10;0; errors_bond0.2421=0c;5;10;0; errors_bond0.224=0c;5;10;0; errors_bond0.2414=0c;5;10;0; errors_bond0.2411=0c;5;10;0; errors_bond0.565=0c;5;10;0; errors_bond0.411=0c;5;10;0; errors_bond0=5000c;5;10;0; errors_bond0.114=0c;5;10;0; errors_bond0.194=0c;5;10;0; errors_eno1=5000c;5;10;0; errors_bond0.2417=0c;5;10;0; errors_bond0.234=0c;5;10;0; errors_bond0.134=0c;5;10;0; errors_bond0.144=0c;5;10;0; errors_bond0.25=0c;5;10;0; errors_bond0.2400=0c;5;10;0; errors_bond0.2423=0c;5;10;0; errors_bond0.2422=0c;5;10;0; errors_bond0.425=0c;5;10;0; errors_bond0.241=0c;5;10;0; errors_bond0.422=0c;5;10;0; errors_bond0.2412=0c;5;10;0; errors_bond0.154=0c;5;10;0;`

I'm using:
#  Version: 2.0.0                                     #
#  Created: 2012-08-13                                #
#  Last Update: 2018-10-19

Many thanks in advance!

Best regards
David

**Comment by scrat14** [comment]
The main idea was to display the errors in performance data which are shown in the ifconfig command/API. So I guess you had 5000 errors and they will stay on the system until a reboot is scheduled.
For Icinga alerting only the difference to last check is counted. That's the reason for the mismatch between actual errors and performance data.

**Comment by davixd** [comment]
Thank you very much for the explanation.
